server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  servlet:
    multipart:
      max-file-size: 10MB        # 限制单个文件的最大值
      max-request-size: 20MB   # 限制上传的多个文件的总大小
  application:
    name: demo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat
        initial-size: 8
        max-active: 20
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        max-wait: 60000
        min-evictable-idle-timeMillis: 300000
        min-idle: 1
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runsMillis: 60000
        use-global-data-source-stat: true
        validation-query: select 'x' FROM DUAL
      filters: stat
      initial-size: 5
      max-active: 21
      max-wait: 100
      min-idle: 6
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/mytest?serverTimezone=UTC
      username: root
      password: 141535
  devtools:
    restart:
      # additional-paths: src/main/resource/
      trigger-file: trigger.txt
      enabled: true
      exclude: WEB-INF/**
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: 0
    host: 127.0.0.1
    password: 141535
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        port: 6379
    timeout: 10000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
